#!/usr/bin/env python
#-*- coding: utf-8 -*-

#202007 kojh create
#-------------------------------------------------------------------------------
import sys
import os
import argparse
from argparse import RawTextHelpFormatter
import time
import datetime
import logging
import traceback

#-------------------------------------------------------------------------------
from module_core import lmt_runner
from module_core import lmt_util

#-------------------------------------------------------------------------------
# 3rd party dependencies
import colorlog
#-------------------------------------------------------------------------------

#///////////////////////////////////////////////////////////////////////////////
#///////////////////////////////////////////////////////////////////////////////
def main(argv):

    # pkg_test [PKG_DIR] [OPTION]
    parser = argparse.ArgumentParser(prog=argv[0],formatter_class=RawTextHelpFormatter)
    parser.add_argument('pkg_dir', type=str, help='package directory full path')
    parser.add_argument('-g','--group', required=False,action='append',  
            help="-g [group name] \n"
            "ex) pkg_test ./packages/POFCS -g group_19.12.0\n"
            "ex) pkg_test ./packages/POFCS -g group_18.10.1 -g group_19.12.0\n\n")

    parser.add_argument('-t','--test_id', required=False,action='append',  
            help="-t [group name].[test name] \n"
            "ex) pkg_test ./packages/POFCS -t group_19.12.0.MES_Alarm\n"
            "ex) pkg_test ./packages/POFCS -t group_19.12.0.MES_Alarm  -t group_19.12.0.VLD_Validation\n\n")

    parser.add_argument('-s','--spec', required=False,action='append',  
            help="\n-s [group name].[test name].[tspec name] \n"
            "ex) pkg_test ./packages/POFCS -s group_19.12.0.MES_Alarm.mes_alarm_valid_time\n"
            "ex) pkg_test ./packages/POFCS -s group_19.12.0.MES_Alarm.mes_alarm_valid_time  "
                "-s group_19.12.0.MES_Alarm.mes_alarm_no_check\n\n")

    # report file name 을 사용자가 지정할수 있게
    parser.add_argument('-f','--filename', required=False,  
            help="-f [report file name] \n"
            "ex) pkg_test ./packages/POFCS -f my_report_name -t group_19.12.0.MES_Alarm \n")

    args = parser.parse_args()

    if(args.pkg_dir.endswith(os.sep) != True) :
        args.pkg_dir += os.sep

    start_dtime = datetime.datetime.now()

    logger = logging.getLogger("pkg_test_log")
    stream_hander = colorlog.StreamHandler()
    stream_hander.setFormatter(colorlog.ColoredFormatter(
	    '%(log_color)s %(asctime)s %(levelname)8s %(funcName)24s:%(lineno)4d  %(message)s',
        datefmt=None, reset=True,
        log_colors={'DEBUG':'cyan', 'INFO':'green', 'WARNING':'yellow', 
                    'ERROR':'red', 'CRITICAL':'red,bg_white',
                    'GRPLOG' : 'blue'},
        secondary_log_colors={}, style='%'))
    logger.addHandler(stream_hander)
    #XXX 처음은 info level로 시작되고, lmt_runner.py 에서 재설정됨
    logger.setLevel(logging.INFO) 

    # result file 
    result_dir_path = args.pkg_dir + "pkg_test_result"
    if not os.path.exists(result_dir_path):
        logger.info("create result dir : {}".format(result_dir_path))
        os.mkdir(result_dir_path)

    timestamp = start_dtime.strftime('%Y%m%d_%H%M%S')
    logger_summary = logging.getLogger("report_summary")
    logger_summary.setLevel(logging.INFO) 
    file_handler = None
    if args.filename :
        args.filename = args.filename.strip()
        logger.info("report file name : {}".format(args.filename))
        file_handler = logging.FileHandler('{}/{}_{}.txt'.
                format(result_dir_path, timestamp, args.filename ))
        file_handler_summary = logging.FileHandler('{}/{}_{}_summary.txt'.
                format(result_dir_path, timestamp, args.filename ))
    else:    
        # ex) 20200620172022_auto_test_report.txt
        file_handler = logging.FileHandler('{}/{}_auto_test_report.txt'.
                format(result_dir_path, timestamp ))
        # ex) 20200620172022_auto_test_summary.txt
        file_handler_summary = logging.FileHandler('{}/{}_auto_test_summary.txt'.
                format(result_dir_path, timestamp ))

    file_handler.setFormatter( logging.Formatter('%(asctime)s %(funcName)24s:%(lineno)4d %(message)s'))
    logger.addHandler(file_handler)

    logger_summary.addHandler(file_handler_summary)

    msg = "---------------------------------------------------------"
    logger.info        (msg)
    logger_summary.info(msg)
    msg = "TEST START {}".format(start_dtime.strftime('%Y-%m-%d %H:%M:%S'))
    logger.info        (msg) 
    logger_summary.info(msg)
    msg = "---------------------------------------------------------"
    logger.info        (msg)
    logger_summary.info(msg)
    if(args.group):
        msg = "- run specific group : {} ".format(args.group)
        logger.info        (msg)
        logger_summary.info(msg)
        if(args.test_id  or args.spec):  #if(args.test_id ):
            logger.critical("specific group only. no test/tspec args allowed : {} ".format(args.test_id))
            logger.critical(" ex) pkg_test /CG/PKG_TEST/SOFCS -g group_5G ")
            logger.critical(" ex) pkg_test /CG/PKG_TEST/SOFCS -t group_01.test1 ")
            return False
    elif(args.test_id):
        msg = "- run specific test  : {} ".format(args.test_id)
        logger.info        (msg)
        logger_summary.info(msg)
    elif(args.spec):
        msg = "- run specific tspec  : {} ".format(args.spec)
        logger.info        (msg)
        logger_summary.info(msg)
    else:    
        msg = "- run whole pkg test"
        logger.info        (msg)
        logger_summary.info(msg)


    logger.info("- pkg_dir = {} ".format(args.pkg_dir))
    is_running, count = lmt_util.is_runnig(argv[0])
    if(is_running ==True and count >1 ): # 자기 자신을 포함한 개수를 체크해야함
        msg ="already running. exit"
        logger.error        (msg)
        logger_summary.error(msg)
        return False

    driver = lmt_runner.PkgTestRunner(logger,logger_summary,timestamp,args)
    try:
        #=================================================
        if driver.run_test() == False:
            return False
        #=================================================
    except Exception as e:
        #err_msg = 'error : {} :{}'.format(e.__doc__, e.message)
        #logger.error(err_msg)

        cl, exc, tb = sys.exc_info()
        err_stack = traceback.extract_tb(tb)
        for bt in err_stack:
            logger.error("{}{}".format(driver.cur_indent,bt))
        del tb
        return False
    finally:

        driver.run_teardown_if_any()
        driver.display_run_result()
        end_dtime = datetime.datetime.now()
        elapsed = end_dtime - start_dtime
        msg = "---------------------------------------------------------"
        logger.info        (msg)
        logger_summary.info(msg)

        seconds = elapsed.total_seconds()
        if(seconds >=  60) :
            hours   = int(seconds / 3600)
            minutes = int(seconds / 60) % 60
            secs    = int(seconds % 60)
            msg ="TEST END   {} -> elapsed : ({})hours ({})minutes ({})seconds".format(end_dtime.strftime('%Y-%m-%d %H:%M:%S'), hours, minutes, secs)
        else:
            msg ="TEST END   {} -> elapsed : ({}) seconds".format(end_dtime.strftime('%Y-%m-%d %H:%M:%S'), seconds )

        logger.info        (msg)
        logger_summary.info(msg)
        if(args.group):
            logger.info("- specific group : {} ".format(args.group))
        elif(args.test_id):
            logger.info("- specific test  : {} ".format(args.test_id))
        elif(args.spec):
            logger.info("- specific tspec : {} ".format(args.spec))
        else:    
            logger.info("- whole pkg test")
        msg = "---------------------------------------------------------"
        logger.info        (msg)
        logger_summary.info(msg)

        driver.clean_all() # XXX
    
    return True        


#///////////////////////////////////////////////////////////////////////////////
if __name__ == "__main__":
    if main(sys.argv):
        sys.exit(0)

    sys.exit(-1)


        
