#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
test automation framework

"""
#-------------------------------------------------------------------------------
import sys
import os
import argparse
from argparse import RawTextHelpFormatter
import time
import datetime
import logging

#-------------------------------------------------------------------------------
from core import pkg_test_runner

#-------------------------------------------------------------------------------
# 3rd party dependencies
import colorlog
#-------------------------------------------------------------------------------

#///////////////////////////////////////////////////////////////////////////////
#///////////////////////////////////////////////////////////////////////////////
def main(argv):

    # pkg_test [PKG_DIR] [OPTION]
    parser = argparse.ArgumentParser(prog=argv[0],formatter_class=RawTextHelpFormatter)
    parser.add_argument('pkg_dir', type=str, help='package directory full path')
    parser.add_argument('-t','--test_id', required=False,action='append',  \
            help="specific test id. -t [group name].[test name] "
            "\n\nex)\n"
            "pkg_test /CG/PKG_TEST/SOFCS -t GROUP_5G.CDC_REDIS_INSERT_001\n")
    """
    parser.add_argument('-p','--parallel', required=False,type=str,  \
            help= "parallel test. need group info. -p -g [group name]\n ")
        "\nex) \n" 
        "pkg_test /CG/PKG_TEST/SOFCS\n" 
        "pkg_test /CG/PKG_TEST/SOFCS -t GROUP_5G.CDC_REDIS_INSERT_001\n"
        "pkg_test /CG/PKG_TEST/SOFCS -p -g GROUP_5G\n" )
    """
    args = parser.parse_args()

    #pkg_dir = os.path.abspath(os.path.expanduser(os.path.expandvars(argv[1])))

    logger = logging.getLogger("auto_tester")
    logger.setLevel(logging.INFO)
    logger.setLevel(logging.DEBUG) # DEBUG, INFO, WARNING, ERROR, CRITICAL
    stream_hander = colorlog.StreamHandler()
    stream_hander.setFormatter(colorlog.ColoredFormatter(
	    '%(log_color)s %(asctime)s %(levelname)8s %(funcName)24s:%(lineno)4d  %(message)s',
        datefmt=None, reset=True,
        log_colors={'DEBUG':'cyan', 'INFO':'green', 'WARNING':'yellow', 
                    'ERROR':'red', 'CRITICAL':'red,bg_white' },
        secondary_log_colors={}, style='%'))
    logger.addHandler(stream_hander)
    logger.debug("arg : pkg_dir = {} ".format(args.pkg_dir))

    cur_dtime = datetime.datetime.now()
    logger.info(" ")
    logger.info("{} start".format(cur_dtime.strftime('%Y-%m-%d %H:%M:%S')))
    #work_day = cur_dtime.strftime('%Y%m%d') 

    try:
        #=================================================
        driver = pkg_test_runner.PkgTestRunner(logger,args)
        if driver.run_test() == False:
            return False
        #=================================================
        cur_dtime = datetime.datetime.now()
        logger.info(" ")
        logger.info("{} end".format(cur_dtime.strftime('%Y-%m-%d %H:%M:%S')))
    except Exception as e:
        err_msg = 'error : {} :{}'.format(e.__doc__, e.message)
        logger.error(err_msg)
        return False
    
    return True        


#///////////////////////////////////////////////////////////////////////////////
if __name__ == "__main__":
    if main(sys.argv):
        sys.exit(0)

    sys.exit(-1)


        
